chatfunction: true
chatPrefixes: false
chatSpacer: "§7› "
tabPrefixes: true
whiteTabNames: false
nametagPrefixes: false
grayNametags: false
rankPrefixFormat: "{RankColour}{RankPrefix}{PlusOption}§7 ¦ "