chatfunction: true
# between [ and ] will only be shown if the Rank-Prefix isn't null!
chatFormat: "{RankColour}{PlayerName}§7› §f{Message}"
tablistFormat: "[{RankColour}{RankPrefix}{PlusOption} §7¦ ]{RankColour}{PlayerName}"
teamColour: "f"
nametagPrefixFormat: ""